Overhaul filter documentation.
pingidentity/scim2 pull request #205
Opened 2023-08-24 16:39 UTC by kqarryzada

This commit enhances the Javadocs for the Filter class and its
subclasses with additional background and more detailed descriptions.
The goal is to give enough detail so that SDK clients are not forced to
refer to the RFC for basic SCIM concepts.

JiraIssue: DS-47822

2023-08-28 17:20 UTC, braveulysses requested changes
Great work, @kqarryzada. Some of my requests for changes are a matter of editorial style, and whether they should be addressed is up to you. 

However, I did see some _existing_ Javadoc problems that should be corrected; I noted those with a comment near the top of `Filter`.

2023-08-28 17:20 UTC, braveulysses commented on scim2-sdk-common/src/main/java/com/unboundid/scim2/common/filters/Filter.java
> + *   Filter filterObject = Filter.fromString(stringFilter);
Consider clarifying this example by echoing the previous example, like this:

```java
Filter filterObject = Filter.fromString("nickName eq \"Alice\"");
```

2023-08-28 17:20 UTC, braveulysses commented on scim2-sdk-common/src/main/java/com/unboundid/scim2/common/filters/Filter.java
> +   * Indicates whether this filter instance is a {@link CombiningFilter}.
Some Javadocs in this class use the imperative mood ("Append the string representation of the filter") and some do not ("Indicates whether this filter instance..."). Either style should be acceptable, but ideally, we should try to consistently use only one.

2023-08-28 17:20 UTC, braveulysses commented on scim2-sdk-common/src/main/java/com/unboundid/scim2/common/filters/Filter.java
>      return null;
This comment is out of scope for this review, but something to consider for the future is whether we could return an empty collection when we would otherwise return a null.

2023-08-28 17:20 UTC, braveulysses commented on scim2-sdk-common/src/main/java/com/unboundid/scim2/common/filters/Filter.java
>     * @return {@code true} if this filter is an {@code and} or {@code or} logical
We could improve the original text somewhat by referring directly to the AndFilter and OrFilter classes:

```java
   * @return {@code true} if this filter is an {@link AndFilter} or an {@link OrFilter} logical
   * combining filter, or {@code false} otherwise.
```

2023-08-28 17:20 UTC, braveulysses commented on scim2-sdk-common/src/main/java/com/unboundid/scim2/common/filters/Filter.java
>  /**
Here are some comments that pertain to existing code. Since these lines weren't changed in the patch, I guess GitHub doesn't let me comment on them directly.

Line 372 (`Filter eq(final String attributePath, final String filterValue)`):
Nit: For consistency, `@return A new equality filter.` could be changed to `@return A new {@code equal} filter.`

Line 613 (`Filter ew(final Path attributePath, final ValueNode filterValue)`):
`@return A new {@code starts with} filter.` should be `@return A new {@code ends with} filter.`

Line 627 (`Filter ew(final String attributePath, final String filterValue)`):
Same as above.

Line 875 (`Filter lt(final Path attributePath, final ValueNode filterValue)`):
`@return A new {@code greater than or equal} filter.` should be `@return A new {@code less than} filter.`

Line 889 (`Filter lt(final Path attributePath, final Integer filterValue)`):
`@return A new {@code greater than or equal} filter.` should be `@return A new {@code less than} filter.`

... and so on for the `lt(...)` methods.

2023-08-28 17:20 UTC, braveulysses commented on scim2-sdk-common/src/main/java/com/unboundid/scim2/common/filters/AndFilter.java
> + * filters generally only have two components.
Maybe... But it seems like the important point is that `AndFilter` and `OrFilter` require _at least two components_.

With that in mind, I'm not sure that we ought to include this paragraph, and earlier statements like... 
>  An AND filter allows a SCIM client to specify two different filter criteria, where both criteria must match a resource.

... arguably should instead be expressed as

>  An AND filter allows a SCIM client to specify multiple filter criteria, where all criteria must match a resource.

2023-08-28 17:20 UTC, braveulysses commented on scim2-sdk-common/src/main/java/com/unboundid/scim2/common/filters/ComparisonFilter.java
> + * values of SCIM resources. For example, an {@link EqualFilter} is a comparison
Nit: Put the example in a separate paragraph. 

My thinking here is that `ComplexValueFilter` establishes a good, readable pattern that would also work well here:

1. Summary/definition
2. Example
3. Supplementary information

This comment — if you choose to accept it — also applies to other classes, such as `ContainsFilter` and `EndsWithFilter`.

2023-08-28 17:20 UTC, braveulysses commented on scim2-sdk-common/src/main/java/com/unboundid/scim2/common/filters/OrFilter.java
> + * of the criterion must match. For instance, consider the following filter.
Should be either "at least one criterion must match" or "at least one of the criteria must match".

2023-09-01 16:00 UTC, kqarryzada commented on scim2-sdk-common/src/main/java/com/unboundid/scim2/common/filters/Filter.java
>      return null;
I would really like that change that as well, but I'm not sure what the best way to accomplish that without a breaking change. I suppose we could create a `getSubordinateFilters()` method that returns an empty list instead, and deprecate this one. But I'm not sure how to keep the same name without a breaking change.

2023-09-01 16:00 UTC, kqarryzada commented on scim2-sdk-common/src/main/java/com/unboundid/scim2/common/filters/AndFilter.java
> + * filters generally only have two components.
I've sent you a message about this.

2023-09-01 16:00 UTC, kqarryzada commented on scim2-sdk-common/src/main/java/com/unboundid/scim2/common/filters/ComparisonFilter.java
> + * values of SCIM resources. For example, an {@link EqualFilter} is a comparison
Thanks for the suggestion. I agree that this is generally more optimal. I've rephrased the existing descriptions, so let me know what you think.

2023-09-05 18:35 UTC, vyhhuang approved these changes
This looks good to me.

2023-09-28 22:37 UTC, braveulysses approved these changes
Sorry about the late approval, @kqarryzada! LGTM.

2023-09-28 22:44 UTC, merged